#!/bin/bash

GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1

export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export GTK_THEME=Catppuccin-blue:dark

export XDG_CURRENT_DESKTOP=Hyprland

Hyprland

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
