#!/bin/sh

xrandr --output DP-4 --mode 1920x1080 --rate 144.00 --pos 0x0 --output DVI-D-0 --mode 1920x1080 --rate 144.00 --right-of DP-4

xsetroot -cursor_name left_ptr
feh --bg-scale ~/Wallpapers/cat-sound.png

bspc monitor DP-4 -d I II III IV V 
bspc monitor DVI-D-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#A6E3A1'
bspc config normal_border_color '#BAC2DE'
bspc config active_border_color '#BAC2DE'
